### ISSUE TITLE
ActionsでCIを回す

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderTrophies#7]
```yml
# See:
# https://docs.github.com/en/actions/guides/building-and-testing-nodejs#building-and-testing-your-code
name: Node.js lint and tests in frontend

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm install
          # npm ci
      - name: Build
        working-directory: frontend
        run: |
          npm build
      - name: Test
        working-directory: frontend
        run: |
          npm test
      # TODO: Lint

      # TODO: Integration Test
```
